baseURL: "https://yuhanwang.github.io/"
languageCode: en-us
theme: 
  - "PaperMod"
  - "hugo-embed-pdf-shortcode"
staticDir:
  - static
enableInlineShortcodes: true

params:
  profileMode:
    enabled: true
    title: "Yuhan Wang's Portfolio"
    imageUrl: "/img/profile/profile.png"
    imageTitle: "Yuhan_Embroidery_profile_photo"
    imageWidth: 120
    imageHeight: 120
  fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys:
    - title
    - permalink
    - summary
    - content

  socialIcons:
    - name: "email"
      url: "ywang70@smith.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yuhan-wang-yw/"
    - name: "github"
      url: "https://github.com/Yuhan-Wang-yw"
    - name: "instagram"
      url: "https://www.instagram.com/yaaaarth/"

menu:
  main:
    - identifier: yw
      name: YW
      url: index.html
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: CV
      name: CV
      url: /cv/
      weight: 40
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 40
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON