baseURL: "https://yuhanwang.github.io/"
languageCode: en-us
theme: 
  - "PaperMod"
  - "hugo-embed-pdf-shortcode"
staticDir:
  - static
enableInlineShortcodes: true
enableEmoji: true

params:
  profileMode:
    enabled: true
    title: "Yuhan Wang"
    subtitle: "Hey! Welcome to Yuhan's Portfolio site"
    imageUrl: "/img/profile/profile.png"
    imageTitle: "Yuhan_Embroidery_profile_photo"
    imageWidth: 120
    imageHeight: 120

  socialIcons:
    - name: "email"
      url: "mailto:ywang70@smith.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yuhan-wang-yw/"
    - name: "github"
      url: "https://github.com/yuhanwww"
    - name: "instagram"
      url: "https://www.instagram.com/yaaaarth/"
    - name: "cv"
      url: "/content/cv.md"

  author: ["Yuhan Wang"]

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  hideMeta: true

  cover:
    hidden: true

menu:
  main:
    # - identifier: home
    #   name: YW
    #   url: index.html
    #   weight: 5
    - identifier: intro
      name: Intro
      url: /intro/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    # - identifier: CV
    #   name: CV
    #   url: /cv/
    #   weight: 40
    # - identifier: posts
    #   name: Posts
    #   url: /posts/
    #   weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys:
    - title
    - permalink
    - summary
    - content

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  tag: tags